# Generated by Django 3.2.9 on 2021-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211206_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('branchesEligible', models.CharField(max_length=500)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stipendOffer', models.IntegerField()),
                ('additionalBenefits', models.TextField()),
                ('registerLink', models.URLField()),
                ('deadline', models.DateTimeField()),
                ('publishDate', models.DateTimeField()),
                ('girlsOnly', models.BooleanField()),
            ],
        ),
    ]
