# Generated by Django 3.2.9 on 2021-12-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('notice', models.TextField()),
                ('expiryDate', models.DateTimeField()),
                ('publishDate', models.DateTimeField()),
            ],
        ),
    ]
