# Generated by Django 3.2.9 on 2021-12-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211208_0250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noticeBoard',
            new_name='notices',
        ),
    ]
