# Generated by Django 3.2.9 on 2021-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_noticeboard_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='placedrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.IntegerField()),
                ('companyName', models.CharField(max_length=50)),
                ('accept', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('publishDate', models.DateTimeField()),
                ('companyID', models.IntegerField()),
            ],
        ),
    ]
